spring.application.name=prompt-service
server.port = 8081

spring.data.mongodb.uri = mongodb+srv://mariacybi10_db_user:MariaCybi@promptcluster.kcg8cng.mongodb.net/?appName=PromptCluster
spring.data.mongodb.database = details